server:
  port: 5000
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    '[org.springframework.boot.web]': INFO

msds:
  back:
    home-uri: http://homefarm-env.eba-c9f3xbye.ap-northeast-2.elasticbeanstalk.com
  front:
    home-uri: http://localhost:3000

kakao:
  auth:
    redirect-uri: http://msds-v2-nlb-fae0e679a067aaf3.elb.ap-northeast-2.amazonaws.com/kakao/callback

naver:
  auth:
    redirect-uri: http://msds-v2-nlb-fae0e679a067aaf3.elb.ap-northeast-2.amazonaws.com/naver/callback

config:
  cors:
    allowed-origin: http://localhost:3000/
