server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=Asia/Seoul
    username: root
    password: endyd132!!

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

msds:
  back:
    home-uri: http://localhost:8080
  front:
    home-uri: http://localhost:3000

kakao:
  auth:
    redirect-uri: http://localhost:8080/kakao/callback

naver:
  auth:
    redirect-uri: http://localhost:8080/naver/callback

config:
  cors:
    allowed-origin: http://localhost:3000/
